# Project information
site_name: 'DAF365 Documentation'
site_description: 'To explain the setup and uses of Office 365 applications'
site_author: 'Randy Rowland'
site_url: 'https://rowland007.github.io/DAF365-Docs/'

# Repository
repo_name: 'Randy Rowland'
repo_url: 'https://github.com/rowland007/'

# Copyright
copyright: 'Copyright &copy; 2022 Randall Rowland<br>This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License.'

# Navigation Menu
nav:
    - Overview: 'index.md'
    - How to use the template:
        'Overview': 'template/index.md'
        'More Info': 'template/info.md'
    - About Mkdocs:
        'Overview': 'mkdocs/index.md'
    - Documentation Style:
        'Overview': 'style/index.md'
    - Appendix 1 - Resources: 'resources.md'

# Configuration
theme:
  name: material
  palette:
    - scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
    - scheme: default
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    admonition:
      cite: octicons/link-external-16
    logo: material/file-document-edit-outline
  favicon: static/images/favicon.png

# Customization
extra:
  social:
    - icon: material/web
      link: https://randyrowland.me
    - icon: fontawesome/brands/github
      link: https://github.com/rowland007
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/randall-rowland-jr
    - icon: material/email
      link: mailto:randall.rowland.1@us.af.mil
  generator: false

# Extensions
markdown_extensions:
  - abbr
  - pymdownx.critic
  - pymdownx.caret
  - md_in_html
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - tables
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg